version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: apisolid
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: apisolid
    ports:
      - 5433:5432

volumes:
  postgres-data:
